const armasPadrao = [
  { categoria: "Armas Simples", grupo: "Corpo-a-corpo - Leves", nome: "Adaga", dano: "1d4", critico: "19-20", distancia: "3M", tipo: "Perf"},
  { categoria: "Armas Simples", grupo: "Corpo-a-corpo - Leves", nome: "Ataque desarmado", dano: "1d3", critico: "x2", distancia: "-", tipo: "Esmag"},
  { categoria: "Armas Simples", grupo: "Corpo-a-corpo - Leves", nome: "Espada Curta", dano: "1d6", critico: "19-20", distancia: "-", tipo: "Perf"},
  { categoria: "Armas Simples", grupo: "Corpo-a-corpo - Leves", nome: "Manopla", dano: "1d4", critico: "x2",distancia: "-", tipo: "Esmag"},
  { categoria: "Armas Simples", grupo: "Corpo-a-corpo - Uma Mão", nome: "Clava", dano: "1d6", critico: "x2", distancia: "-", tipo: "Esmag"},
  { categoria: "Armas Simples", grupo: "Corpo-a-corpo - Uma Mão", nome: "Lança", dano: "1d6", critico: "x2", distancia: "6M", tipo: "Perf"},
  { categoria: "Armas Simples", grupo: "Corpo-a-corpo - Uma Mão", nome: "Maça", dano: "1d8", critico: "x2", distancia: "-", tipo: "Esmag"},
  { categoria: "Armas Simples", grupo: "Corpo-a-corpo - Duas Mãos", nome: "Bordão", dano: "1d6/1d6", critico: "x2", distancia: "-", tipo: "Esmag"},
  { categoria: "Armas Simples", grupo: "Corpo-a-corpo - Duas Mãos", nome: "Pique", dano: "1d8", critico: "x2", distancia: "-", tipo: "Perf"},
  { categoria: "Armas Simples", grupo: "Corpo-a-corpo - Duas Mãos", nome: "Tacape", dano: "1d10", critico: "x2", distancia: "-", tipo: "Esmag"},
  { categoria: "Armas Simples", grupo: "Ataque à Distância", nome: "Ácido", dano: "2d4", critico: "-", distancia: "3M", tipo: "Ácido"},
  { categoria: "Armas Simples", grupo: "Ataque à Distância", nome: "Água benda", dano: "2d6", critico: "-", distancia: "3M", tipo: "Espacial"},
  { categoria: "Armas Simples", grupo: "Ataque à Distância", nome: "Arco Curto", dano: "1d6", critico: "x3", distancia: "12M", tipo: "Perf"},
  { categoria: "Armas Simples", grupo: "Ataque à Distância", nome: "Azagia", dano: "1d6", critico: "x2", distancia: "9M", tipo: "Perf"},
  { categoria: "Armas Simples", grupo: "Ataque à Distância", nome: "Besta leve", dano: "1d8", critico: "19-20", distancia: "18M", tipo: "Perf"},
  { categoria: "Armas Simples", grupo: "Ataque à Distância", nome: "Fogo alquímico", dano: "1d6", critico: "-", distancia: "3M", tipo: "Fogo"},
  { categoria: "Armas Simples", grupo: "Ataque à Distância", nome: "Funda", dano: "1d4", critico: "x2", distancia: "15M", tipo: "Esmag"},
  { categoria: "Armas Simples", grupo: "Ataque à Distância", nome: "Granada", dano: "4d6", critico: "-", distancia: "3M", tipo: "Fogo"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Leves", nome: "Escudo leve", dano: "1d4", critico: "x2", distancia: "-", tipo: "Esmag"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Leves", nome: "Machadinha", dano: "1d6", critico: "x3", distancia: "3M", tipo: "Cort"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Leves", nome: "Martelo", dano: "1d6", critico: "x2", distancia: "6M", tipo: "Esmag"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Uma mão", nome: "Cimitarra", dano: "1d6", critico: "18-20", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Uma mão", nome: "Escudo pesado", dano: "1d6", critico: "x2", distancia: "-", tipo: "Esmag"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Uma mão", nome: "Espada longa", dano: "1d8", critico: "19-20", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Uma mão", nome: "Florete", dano: "1d6", critico: "18-20", distancia: "-", tipo: "Perf"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Uma mão", nome: "Machado de batalha", dano: "1d8", critico: "x3", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Uma mão", nome: "Mangual", dano: "1d8", critico: "x2", distancia: "-", tipo: "Esmag"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Uma mão", nome: "Martelo de guerra", dano: "1d8", critico: "x3", distancia: "-", tipo: "Esmag"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Uma mão", nome: "Picareta", dano: "1d6", critico: "x4", distancia: "-", tipo: "Perf"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Uma mão", nome: "Tridente", dano: "1d8", critico: "x2", distancia: "-", tipo: "Perf"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Duas mãos", nome: "Alabarda", dano: "1d10", critico: "x3", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Duas mãos", nome: "Alfange", dano: "2d4", critico: "18-20", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Duas mãos", nome: "Espaga grande", dano: "2d6", critico: "19-20", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Duas mãos", nome: "Foice", dano: "2d4", critico: "x4", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Duas mãos", nome: "Lança montada", dano: "1d8", critico: "x3", distancia: "-", tipo: "Perf"},
  { categoria: "Armas Marciais", grupo: "Corpo-a-corpo - Duas mãos", nome: "Machado grande", dano: "1d12", critico: "x3", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Marciais", grupo: "Ataque à Distância", nome: "Arco composto", dano: "1d6", critico: "x3", distancia: "18M", tipo: "Perf"},
  { categoria: "Armas Marciais", grupo: "Ataque à Distância", nome: "Arco longo", dano: "1d8", critico: "x3", distancia: "24M", tipo: "Perf"},
  { categoria: "Armas Marciais", grupo: "Ataque à Distância", nome: "Besta pesada", dano: "1d12", critico: "19-20", distancia: "27M", tipo: "Perf"},
  { categoria: "Armas Exóticas", grupo: "Corpo-a-corpo - Leves", nome: "Nunchaku", dano: "1d6", critico: "x3", distancia: "-", tipo: "Esmag"},
  { categoria: "Armas Exóticas", grupo: "Corpo-a-corpo - Leves", nome: "Sai", dano: "1d6", critico: "x2", distancia: "3M", tipo: "Esmag"},
  { categoria: "Armas Exóticas", grupo: "Corpo-a-corpo - Leves", nome: "Wakizashi", dano: "1d8", critico: "19-20", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Exóticas", grupo: "Corpo-a-corpo - Uma mão", nome: "Chicote", dano: "1d3", critico: "x2", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Exóticas", grupo: "Corpo-a-corpo - Uma mão", nome: "Espada bastardea", dano: "1d10", critico: "19-20", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Exóticas", grupo: "Corpo-a-corpo - Uma mão", nome: "Katana", dano: "1d10", critico: "19-20", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Exóticas", grupo: "Corpo-a-corpo - Uma mão", nome: "Machado anão", dano: "1d10", critico: "x3", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Exóticas", grupo: "Corpo-a-corpo - Uma mão", nome: "Sabre serrilhado", dano: "1d8", critico: "19-20/Esp", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Exóticas", grupo: "Corpo-a-corpo - Duas mãos", nome: "Corrente com cravos", dano: "2d4", critico: "x2", distancia: "-", tipo: "Perf"},
  { categoria: "Armas Exóticas", grupo: "Corpo-a-corpo - Duas mãos", nome: "Espada de duas lâminas", dano: "1d8/1d8", critico: "19-20", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Exóticas", grupo: "Corpo-a-corpo - Duas mãos", nome: "Espada táurica", dano: "2d8", critico: "x2", distancia: "-", tipo: "Cort"},
  { categoria: "Armas Exóticas", grupo: "Corpo-a-corpo - Duas mãos", nome: "Marreta estilhaçadora", dano: "1d12", critico: "19-20/Esp", distancia: "-", tipo: "Esmag"},
  { categoria: "Armas Exóticas", grupo: "Ataque à Distância", nome: "Mosquete", dano: "2d8", critico: "19-20/x3", distancia: "45M", tipo: "Perf"},
  { categoria: "Armas Exóticas", grupo: "Ataque à Distância", nome: "Pistola", dano: "2d6", critico: "19-20/x3", distancia: "15M", tipo: "Perf"},
  { categoria: "Armas Exóticas", grupo: "Ataque à Distância", nome: "Rede", dano: "-", critico: "-", distancia: "3M", tipo: "-"},
  { categoria: "Armas Exóticas", grupo: "Ataque à Distância", nome: "Shuriken", dano: "1d4", critico: "x2", distancia: "3M", tipo: "Perf"},
  { categoria: "Armas Exóticas", grupo: "Ataque à Distância", nome: "Tai-tai", dano: "2d4", critico: "x2", distancia: "24M", tipo: "Esmag"}
];

// Estrutura agrupada por categoria > grupo
const estrutura = {};
armasPadrao.forEach((arma, i) => {
  if (!estrutura[arma.categoria]) estrutura[arma.categoria] = {};
  if (!estrutura[arma.categoria][arma.grupo]) estrutura[arma.categoria][arma.grupo] = [];
  estrutura[arma.categoria][arma.grupo].push({ ...arma, index: i });
});